Canopen stack sys
neurio/penguin-fork-canopen-stack pull request #1
Opened 2023-02-15 22:55 UTC by AustinF93

Changes required for the Rust implementation of canopen-stack for Penguin

2023-02-16 22:23 UTC, awm requested changes
Do we need a separate fork of the CANopen Stack for this?  We already have a repository for the fork, and I'm not sure that we need a second one.  Any bug fixes or improvements should go into the existing repo, and any wrappers needed to make it work with Rust should go into the repository for the PWRtalk agent, I think.

2023-02-16 22:23 UTC, awm commented on src/core/co_core.h
> +#include "co_penguin_cfg.h"
Rather than modifying the stack's source, we should just have a custom `co_cfg.h` in a separate directory and use include paths to select it rather than the default.  That file can also then include any custom headers you need.

2023-02-16 22:23 UTC, awm commented on src/core/co_core.h
> +    const struct CO_EMCY_TBL_T      *EmcyCode;     /*!< application EMCY info fields   */
Why does this need to be changed to `const`?

2023-02-16 22:23 UTC, awm commented on src/core/co_nmt.c
> -
In general, it keeps the history cleaner if we avoid committing whitespace-only changes if there are no other more substantive modifications to the file.

2023-02-16 22:23 UTC, awm commented on src/core/co_core.h
> +
It's not clear to me what this is for.  If there's some state you need to access in the various HAL callbacks, can you not just create a separate C file that implements the getter/setter, and then call that function where necessary in the HAL implementations rather than modifying all of the interfaces of the third party code?

2023-02-17 14:23 UTC, AustinF93 commented on src/core/co_core.h
> +    const struct CO_EMCY_TBL_T      *EmcyCode;     /*!< application EMCY info fields   */
Looks like I did that to match the auto generated code which creates the emergency table as a constant. The better idea would be to change the auto generated code to change this from being a constant

2023-02-17 14:33 UTC, AustinF93 commented on src/core/co_core.h
> +
I am going to try this. You make an excellent point. It would be much better f or me to wrap the canopen-stack code with my own C files so we can all use the same canopen-stack fork and I do not have to modify the source for Rust specific implementation needs

2024-12-05 23:29 UTC, closed without merging